# Generated by Django 2.2.26 on 2022-07-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_link',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
