# Generated by Django 2.2.26 on 2022-08-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20220807_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Requested', 'Requested'), ('Accepted', 'Accepted'), ('In transit', 'In transit'), ('Received', 'Received'), ('Cancelled', 'Cancelled')], default='Unpaid', max_length=64),
        ),
    ]
