# Generated by Django 2.2.28 on 2022-08-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20220809_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_paid',
            field=models.BooleanField(default=False),
        ),
    ]
