# Generated by Django 2.2.28 on 2022-12-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20220920_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_link',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
