# Generated by Django 2.2.28 on 2022-12-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20221225_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_link',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
