# Generated by Django 2.2.28 on 2023-02-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20221225_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Requested', 'Requested'), ('Accepted', 'Accepted'), ('In transit', 'In transit'), ('Received', 'Received'), ('Cancelled', 'Cancelled')], default='Requested', max_length=64),
        ),
    ]
