# Generated by Django 2.2.28 on 2022-08-12 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push_notification', '0004_auto_20220812_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_send',
            new_name='is_sent',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='users',
            new_name='user',
        ),
    ]
