# Generated by Django 2.2.28 on 2022-08-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notification', '0005_auto_20220812_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
