# Generated by Django 2.2.28 on 2023-02-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notification', '0008_auto_20230209_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='object_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
