# Generated by Django 2.2.28 on 2023-02-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notification', '0009_auto_20230210_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
