# Generated by Django 2.2.26 on 2022-07-23 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_order_qr_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('amount_before_transaction', models.FloatField()),
                ('amount_after_transaction', models.FloatField()),
                ('trans_type', models.CharField(choices=[('d', 'Debit'), ('c', 'Credit')], db_index=True, max_length=1)),
                ('payment_type', models.CharField(choices=[('ST', 'Stripe'), ('TZ', 'Tazapay')], db_index=True, max_length=2)),
                ('details', models.CharField(max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_transaction', to='orders.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_transaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_transaction',
            },
        ),
    ]
