# Generated by Django 2.2.28 on 2022-06-24 07:20

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('One Way', 'One Way'), ('Round Trip', 'Round Trip')], max_length=64)),
                ('departure_city', models.CharField(max_length=255)),
                ('departure_state', models.CharField(max_length=255)),
                ('departure_country', models.CharField(max_length=255)),
                ('arrival_city', models.CharField(max_length=255)),
                ('arrival_state', models.CharField(max_length=255)),
                ('arrival_country', models.CharField(max_length=255)),
                ('date_of_journey', models.DateField()),
                ('date_of_return', models.DateField(blank=True, null=True)),
                ('willing_to_carry', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Electronics', 'Electronics'), ('Jewelry', 'Jewelry'), ('Documents and Books', 'Documents and Books'), ('Food items', 'Food items'), ('Clothing', 'Clothing'), ('Medication', 'Medication')], max_length=64), blank=True, null=True, size=None)),
                ('total_weight', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
