# Generated by Django 2.2.26 on 2022-08-03 12:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20220731_1640'),
        ('journeys', '0002_journey_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('delivered', 'Delivered')], default='pending', max_length=65)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journeys.Journey')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
            options={
                'db_table': 'journey_order_request',
                'unique_together': {('journey', 'order')},
            },
        ),
    ]
