# Generated by Django 2.2.26 on 2022-08-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0003_journeyorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journeyorder',
            name='status',
        ),
        migrations.AddField(
            model_name='journeyorder',
            name='allowed_by_carrier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journeyorder',
            name='allowed_by_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journeyorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='journeyorder',
            table='journey_order',
        ),
    ]
