# Generated by Django 2.2.28 on 2022-11-11 18:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20220920_1914'),
        ('journeys', '0004_auto_20220806_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclineJourneyOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journeys.Journey')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
            options={
                'db_table': 'decline_journey_order',
            },
        ),
    ]
