# Generated by Django 2.2.26 on 2022-08-07 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journeys', '0004_auto_20220806_1841'),
        ('orders', '0009_auto_20220807_1427'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.FloatField(null=True)),
                ('content', models.TextField(max_length=1000, null=True)),
                ('respectful_attitude', models.BooleanField(null=True)),
                ('no_additional_payment_asked', models.BooleanField(null=True)),
                ('d2d_delivery', models.BooleanField(null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
                ('journey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_review', to='journeys.Journey')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_review', to='orders.Order')),
                ('target_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews_review',
            },
        ),
    ]
