# Generated by Django 2.2.28 on 2022-08-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportrequest',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
