# Generated by Django 2.2.28 on 2022-08-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20220803_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='categories',
            field=models.CharField(choices=[('ORDER', 'ORDER'), ('BASIC', 'BASIC'), ('JOURNEY', 'JOURNEY'), ('PAYMENT', 'PAYMENT'), ('VERIFICATION', 'VERIFICATION')], default='BASIC', max_length=10),
        ),
    ]
