# Generated by Django 2.2.28 on 2022-08-25 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_faq_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='file',
        ),
        migrations.RemoveField(
            model_name='supportrequest',
            name='file',
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='SupportRequestMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/support_request/')),
                ('support_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.SupportRequest')),
            ],
            options={
                'verbose_name': 'SupportRequest Media',
                'verbose_name_plural': 'SupportRequest Medias',
            },
        ),
        migrations.CreateModel(
            name='FeedbackMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/feedback/')),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Feedback')),
            ],
            options={
                'verbose_name': 'Feedback Media',
                'verbose_name_plural': 'Feedback Medias',
            },
        ),
    ]
