# Generated by Django 2.2.28 on 2022-08-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_auto_20220825_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/support_request/'),
        ),
    ]
