# Generated by Django 2.2.28 on 2022-08-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_auto_20220825_1047'),
        ('support', '0004_auto_20220825_1433'),
    ]

    operations = [
    ]
