# Generated by Django 2.2.26 on 2022-07-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220624_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_amount',
            field=models.FloatField(default=0),
        ),
    ]
