# Generated by Django 2.2.28 on 2022-07-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220724_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verification_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_verification_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
