# Generated by Django 2.2.26 on 2022-08-12 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220729_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPassportImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passport_photo', models.ImageField(upload_to='users/passport')),
                ('current_photo', models.ImageField(upload_to='users/passport')),
                ('is_passport_valid', models.BooleanField(default=False)),
                ('passport_score', models.FloatField(default=0)),
                ('passport_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('is_valid_biometric', models.BooleanField(default=False)),
                ('biometric_score', models.FloatField(default=0)),
                ('biometric_error', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
