# Generated by Django 2.2.26 on 2022-08-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_passport_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='passport_status',
            field=models.CharField(default='Not Applied', max_length=20),
        ),
        migrations.AddField(
            model_name='userpassportimage',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userpassportimage',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userpassportimage',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userpassportimage',
            name='meeting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpassportimage',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
