# Generated by Django 2.2.26 on 2022-08-25 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220825_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpassportimage',
            old_name='meeting_date',
            new_name='meeting_datetime',
        ),
    ]
