# Generated by Django 2.2.28 on 2022-10-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220825_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='send_notification',
            field=models.BooleanField(default=True),
        ),
    ]
